filetype = {}

filetype["ppt"] = {"id": "52000", "name": "Microsoft PowerPoint", "category": "unknown"}
filetype["doc"] = {"id": "52001", "name": "Microsoft Word DOC File", "category": "unknown"}
filetype["xls"] = {"id": "52002", "name": "Microsoft Excel XLS File", "category": "unknown"}
filetype["cab"] = {"id": "52003", "name": "Microsoft Cabinet (CAB)", "category": "unknown"}
filetype["zip"] = {"id": "52004", "name": "ZIP", "category": "unknown"}
filetype["tar"] = {"id": "52005", "name": "TAR", "category": "unknown"}
filetype["hta"] = {"id": "52006", "name": "HTA (HTML Application)", "category": "unknown"}
filetype["pif"] = {"id": "52007", "name": "Windows Program Information File (PIF)", "category": "unknown"}
filetype["reg"] = {"id": "52008", "name": "Windows Registry (REG)", "category": "unknown"}
filetype["bat"] = {"id": "52009", "name": "Windows Batch (BAT)", "category": "unknown"}
filetype["wsf"] = {"id": "52010", "name": "Windows Script (WSF)", "category": "unknown"}
filetype["gzip"] = {"id": "52014", "name": "GZIP", "category": "unknown"}
filetype["rar"] = {"id": "52015", "name": "RAR", "category": "unknown"}
filetype["zcompressed"] = {"id": "52016", "name": "Z Compressed", "category": "unknown"}
filetype["pl"] = {"id": "52017", "name": "Perl Script", "category": "unknown"}
filetype["sh"] = {"id": "52018", "name": "Shell Script", "category": "unknown"}
filetype["dll"] = {"id": "52019", "name": "Windows Dynamic Link Library (DLL)", "category": "unknown"}
filetype["exe"] = {"id": "52020", "name": "Windows Executable (EXE)", "category": "unknown"}
filetype["pdf"] = {"id": "52021", "name": "Adobe PDF File", "category": "unknown"}
filetype["docx"] = {"id": "52022", "name": "Microsoft Word 2007 DOCX File", "category": "unknown"}
filetype["pptx"] = {"id": "52023", "name": "Microsoft PowerPoint 2007 PPTX File", "category": "unknown"}
filetype["xlsx"] = {"id": "52024", "name": "Microsoft Excel 2007 XLSX File", "category": "unknown"}
filetype["pgp"] = {"id": "52025", "name": "Pretty Good Privacy Format (PGP)", "category": "unknown"}
filetype["gz"] = {"id": "52027", "name": "GZIP", "category": "unknown"}
filetype["tif"] = {"id": "52030", "name": "TIF File", "category": "unknown"}
filetype["mdb"] = {"id": "52031", "name": "Microsoft Access Database File", "category": "unknown"}
filetype["msoffice"] = {"id": "52033", "name": "Microsoft MSOFFICE", "category": "unknown"}
filetype["mdi"] = {"id": "52036", "name": "MDI File", "category": "unknown"}
filetype["ocx"] = {"id": "52041", "name": "Activex File", "category": "unknown"}
filetype["wri"] = {"id": "52043", "name": "WRI File", "category": "unknown"}
filetype["rtf"] = {"id": "52044", "name": "RTF File", "category": "unknown"}
filetype["mpeg"] = {"id": "52045", "name": "MPEG File", "category": "unknown"}
filetype["wmv"] = {"id": "52046", "name": "WMV File", "category": "unknown"}
filetype["flv"] = {"id": "52047", "name": "FLV File", "category": "unknown"}
filetype["avi"] = {"id": "52048", "name": "AVI File", "category": "unknown"}
filetype["mov"] = {"id": "52049", "name": "Quicktime MOV File", "category": "unknown"}
filetype["mp3"] = {"id": "52054", "name": "MP3 File", "category": "unknown"}
filetype["psd"] = {"id": "52056", "name": "PSD File", "category": "unknown"}
filetype["sgi"] = {"id": "52057", "name": "SGI File", "category": "unknown"}
filetype["xpm"] = {"id": "52059", "name": "XPM File", "category": "unknown"}
filetype["PE"] = {"id": "52060", "name": "Microsoft PE File", "category": "unknown"}
filetype["svg"] = {"id": "52062", "name": "Scalable Vector Graphics SVG File", "category": "unknown"}
filetype["shk"] = {"id": "52063", "name": "SHK File", "category": "unknown"}
filetype["mb"] = {"id": "52064", "name": "Maya MB File", "category": "unknown"}
filetype["ma"] = {"id": "52065", "name": "Maya ASCII File", "category": "unknown"}
filetype["dpx"] = {"id": "52066", "name": "DPX File", "category": "unknown"}
filetype["gif"] = {"id": "52071", "name": "GIF File", "category": "unknown"}
filetype["jpeg"] = {"id": "52072", "name": "JPEG File", "category": "unknown"}
filetype["wmf"] = {"id": "52076", "name": "WMF File", "category": "unknown"}
filetype["unknown"] = {"id": "52081", "name": "Unknown Binary File", "category": "unknown"}
filetype["iso"] = {"id": "52088", "name": "ISO File", "category": "unknown"}
filetype["msi"] = {"id": "52089", "name": "MSI File", "category": "unknown"}
filetype["torrent"] = {"id": "52090", "name": "Torrent File", "category": "unknown"}
filetype["cmd"] = {"id": "52092", "name": "CMD Windows Script File", "category": "unknown"}
filetype["lzh"] = {"id": "52093", "name": "LZH File", "category": "unknown"}
filetype["lnk"] = {"id": "52094", "name": "LNK File", "category": "unknown"}
filetype["dwg"] = {"id": "52095", "name": "DWG File Detected", "category": "unknown"}
filetype["jpg"] = {"id": "52097", "name": "JPEG File Upload", "category": "unknown"}
filetype["bmp"] = {"id": "52098", "name": "BMP File Upload", "category": "unknown"}
filetype["rm"] = {"id": "52099", "name": "RealMedia File", "category": "unknown"}
filetype["png"] = {"id": "52100", "name": "PNG File Upload", "category": "unknown"}
filetype["mp4"] = {"id": "52104", "name": "MP4 Detected", "category": "unknown"}
filetype["mkv"] = {"id": "52105", "name": "MKV Detected", "category": "unknown"}
filetype["apk"] = {"id": "52108", "name": "Android Package File Detected", "category": "unknown"}
filetype["gds"] = {"id": "52109", "name": "Graphic Data System File Detected", "category": "unknown"}
filetype["tdb"] = {"id": "52110", "name": "Tanner Database File", "category": "unknown"}
filetype["dsn"] = {"id": "52111", "name": "OrCAD DSN File", "category": "unknown"}
filetype["edif"] = {"id": "52112", "name": "EDIF File", "category": "unknown"}
filetype["vbe"] = {"id": "52114", "name": "VBScript Encoded File", "category": "unknown"}
filetype["jar"] = {"id": "52116", "name": "JAR File", "category": "benign"}
filetype["class"] = {"id": "52117", "name": "Java Class File", "category": "unknown"}
filetype["iwork"] = {"id": "52118", "name": "Apple iWork Pages File", "category": "unknown"}
filetype["cdr"] = {"id": "52121", "name": "CorelDRAW File", "category": "unknown"}
filetype["dwf"] = {"id": "52122", "name": "Design Web Format File", "category": "unknown"}
filetype["stp"] = {"id": "52123", "name": "CAD STEP File", "category": "unknown"}
filetype["jpeg"] = {"id": "52136", "name": "JPEG File Upload", "category": "unknown"}
filetype["Email"] = {"id": "52143", "name": "Email Link", "category": "unknown"}
filetype["scr"] = {"id": "52144", "name": "Windows Screen Saver SCR File", "category": "unknown"}
filetype["flash"] = {"id": "52145", "name": "Adobe Shockwave Flash File", "category": "unknown"}
filetype["hlp"] = {"id": "52148", "name": "Windows Help File", "category": "unknown"}
filetype["Multi"] = {"id": "52149", "name": "Multi-Level Encoding", "category": "unknown"}
filetype["catpart"] = {"id": "52150", "name": "Catpart", "category": "unknown"}
filetype["dmg"] = {"id": "52151", "name": "DMG File Detected", "category": "unknown"}
filetype["pkg"] = {"id": "52152", "name": "PKG File Detected", "category": "unknown"}
filetype["mach"] = {"id": "52153", "name": "MACH-O File Detected", "category": "unknown"}
filetype["macapp"] = {"id": "52155", "name": "MacOSX APP File Detected", "category": "unknown"}
filetype["ichitaro"] = {"id": "52156", "name": "JustSystems Ichitaro Document", "category": "unknown"}
filetype["arj"] = {"id": "52157", "name": "ARJ File Detected", "category": "unknown"}
filetype["7z"] = {"id": "52158", "name": "7z File Detected", "category": "unknown"}
filetype["cpl"] = {"id": "52159", "name": "CPL File", "category": "unknown"}
filetype["chm"] = {"id": "52160", "name": "CHM File", "category": "unknown"}
filetype["py"] = {"id": "52166", "name": "Python File", "category": "unknown"}
filetype["mht"] = {"id": "52168", "name": "MIME HTML File", "category": "unknown"}
filetype["deflate64"] = {"id": "52173", "name": "Deflate64 Compressed ZIP", "category": "unknown"}
filetype["ace"] = {"id": "52174", "name": "ACE File", "category": "unknown"}
filetype["elf"] = {"id": "52175", "name": "ELF File", "category": "unknown"}
filetype["webm"] = {"id": "52177", "name": "WEBM File", "category": "unknown"}
filetype["powershell"] = {"id": "52179", "name": "PowerShell Script File", "category": "unknown"}
filetype["hwp"] = {"id": "52181", "name": "HWP file", "category": "unknown"}
filetype["split"] = {"id": "52183", "name": "Split RAR File", "category": "unknown"}
filetype["shs"] = {"id": "52185", "name": "Microsoft Scrap File", "category": "unknown"}
filetype["scf"] = {"id": "52186", "name": "Windows Explorer Shell Command File", "category": "unknown"}
filetype["bzip2"] = {"id": "52187", "name": "BZIP2", "category": "unknown"}
filetype["csv"] = {"id": "52189", "name": "CSV File", "category": "unknown"}
filetype["hwpx"] = {"id": "52191", "name": "HWPX file", "category": "unknown"}
filetype["docm"] = {"id": "52194", "name": "Microsoft Word 2007 DOCM File", "category": "unknown"}
filetype["iqy"] = {"id": "52200", "name": "Excel Web Query File", "category": "unknown"}
filetype["js"] = {"id": "52202", "name": "JS Script File", "category": "unknown"}
filetype["vbs"] = {"id": "52203", "name": "VBScript File", "category": "unknown"}
filetype["jse"] = {"id": "52208", "name": "JScript Encoded File", "category": "unknown"}
filetype["der"] = {"id": "52209", "name": "DER Encoded X509 Certificate", "category": "unknown"}
filetype["pem"] = {"id": "52210", "name": "PEM Encoded X509 Certificate", "category": "unknown"}
filetype["microsoft"] = {"id": "52211", "name": "Microsoft Shell", "category": "unknown"}
filetype["access"] = {"id": "52213", "name": "Access Shortcut File", "category": "unknown"}
filetype["xll"] = {"id": "52214", "name": "Excel Add-in XLL File", "category": "unknown"}
filetype["slk"] = {"id": "52216", "name": "Excel Symbolic Link File", "category": "unknown"}
filetype["aip"] = {"id": "52218", "name": "Microsoft Office 2007 AIP Encrypted File", "category": "unknown"}
filetype["mda"] = {"id": "52221", "name": "Microsoft Access Add-in MDA File", "category": "unknown"}
filetype["mdt"] = {"id": "52222", "name": "Microsoft Access Add-in Data MDT File", "category": "unknown"}
filetype["mdw"] = {"id": "52223", "name": "Microsoft Access Workgroup Information MDW File", "category": "unknown"}
filetype["mdz"] = {"id": "52224", "name": "Microsoft Access Wizard Template MDZ File", "category": "unknown"}
filetype["adp"] = {"id": "52225", "name": "Microsoft Access Project ADP File", "category": "unknown"}
filetype["ade"] = {"id": "52226", "name": "Microsoft Access Project Extension ADE File", "category": "unknown"}
filetype["vb"] = {"id": "52227", "name": "VBScript VB File", "category": "unknown"}
filetype["tmp"] = {"id": "52228", "name": "Temporary TMP File", "category": "unknown"}
filetype["url"] = {"id": "52229", "name": "Internet Location URL File", "category": "unknown"}
filetype["wsh"] = {"id": "52230", "name": "Windows Script Host Settings WSH File", "category": "unknown"}
filetype["renamed"] = {"id": "52231", "name": "Renamed Zip File", "category": "unknown"}
filetype["vxd"] = {"id": "52232", "name": "Virtual Device Driver VXD File", "category": "unknown"}
filetype["sys"] = {"id": "52233", "name": "Windows System SYS File", "category": "unknown"}
filetype["inf"] = {"id": "52234", "name": "Setup Information INF File", "category": "unknown"}
filetype["pbix"] = {"id": "52235", "name": "Power-BI PBIX File", "category": "unknown"}
filetype["bas"] = {"id": "52238", "name": "BASIC Source Code BAS File", "category": "unknown"}
filetype["asp"] = {"id": "52239", "name": "Active Server Page ASP File", "category": "unknown"}
filetype["ins"] = {"id": "52240", "name": "Internet Settings INS File", "category": "unknown"}
filetype["its"] = {"id": "52241", "name": "Internet Document Set ITS File", "category": "unknown"}
filetype["com"] = {"id": "52242", "name": "DOS Executable COM File", "category": "unknown"}
filetype["prg"] = {"id": "52244", "name": "Program PRG File", "category": "unknown"}
filetype["msc"] = {"id": "52245", "name": "Microsoft Management Console MSC File", "category": "unknown"}
filetype["msp"] = {"id": "52246", "name": "Windows Installer Patch MSP File", "category": "unknown"}
filetype["gadget"] = {"id": "52247", "name": "Microsoft Windows Gadget File", "category": "unknown"}
filetype["shb"] = {"id": "52248", "name": "Windows Document Shortcut SHB File", "category": "unknown"}
filetype["ops"] = {"id": "52249", "name": "Office Profile Settings OPS File", "category": "unknown"}
filetype["isp"] = {"id": "52250", "name": "IIS Internet Service Provider Settings ISP File", "category": "unknown"}
filetype["job"] = {"id": "52251", "name": "Windows Task Scheduler JOB File", "category": "unknown"}
filetype["lib"] = {"id": "52252", "name": "Generic Data Library LIB File", "category": "unknown"}
filetype["tbz2"] = {"id": "52253", "name": "BZip2 Compressed Tar Archive TBZ2 File", "category": "unknown"}
filetype["jsp"] = {"id": "52255", "name": "JavaServer Pages JSP File", "category": "unknown"}
filetype["php"] = {"id": "52256", "name": "Hypertext Preprocessor PHP File", "category": "unknown"}
filetype["aspx"] = {"id": "52257", "name": "Active Server Page Extended ASPX File", "category": "unknown"}
filetype["dex"] = {"id": "52259", "name": "Dalvik Executable DEX File", "category": "unknown"}
filetype["crx"] = {"id": "52270", "name": "Google Chrome Extension CRX File", "category": "unknown"}
filetype["ico"] = {"id": "52271", "name": "Windows ICON File", "category": "unknown"}
filetype["ogg"] = {"id": "52272", "name": "Ogg Vorbis Audio File", "category": "unknown"}
filetype["hdf"] = {"id": "52273", "name": "Hierarchical Data Format HDF File", "category": "unknown"}
filetype["woff"] = {"id": "52274", "name": "WOFF File Format", "category": "unknown"}
filetype["webp"] = {"id": "52275", "name": "WebP Image File", "category": "unknown"}
filetype["rvt"] = {"id": "52277", "name": "Revit Project File", "category": "unknown"}
filetype["crl"] = {"id": "52280", "name": "Certificate Revocation List File", "category": "unknown"}
filetype["rpm"] = {"id": "52285", "name": "Package Manager RPM File", "category": "unknown"}
filetype["vmdk"] = {"id": "52286", "name": "Virtual Machine Disk VMDK File", "category": "unknown"}
filetype["txt"] = {"id": "52287", "name": "TXT File Upload", "category": "unknown"}
filetype["java"] = {"id": "52289", "name": "Java Source File", "category": "unknown"}
filetype["rb"] = {"id": "52290", "name": "Ruby Source File", "category": "unknown"}
filetype["vhdl"] = {"id": "52291", "name": "VHDL Source File", "category": "unknown"}
filetype["csharp"] = {"id": "52298", "name": "C Sharp Source File", "category": "unknown"}
filetype["ruby"] = {"id": "52300", "name": "Ruby Source File", "category": "unknown"}
filetype["matlab"] = {"id": "52301", "name": "Matlab Mathematica Objective-C Source File", "category": "unknown"}
filetype["verilog"] = {"id": "52304", "name": "Verilog Source File", "category": "unknown"}
filetype["asm"] = {"id": "52305", "name": "Assembly Source File", "category": "unknown"}
filetype["c"] = {"id": "52317", "name": "C CPP Source File", "category": "unknown"}
filetype["h"] = {"id": "52318", "name": "C CPP Header File", "category": "unknown"}
filetype["r"] = {"id": "52319", "name": "R Source File", "category": "unknown"}
filetype["vhd"] = {"id": "52320", "name": "Virtual Hard Disk VHD File", "category": "unknown"}
filetype["kdb"] = {"id": "52321", "name": "Keepass Database File", "category": "unknown"}
