#
# Threats mapping found from various places
# https://www.infoguardsecurity.com/wp-content/uploads/Sample-Cyber-Assessment-Report.pdf
#

threats = [{"risk": "5", "application": "webdav", "category": "general-internet", "subcategory": "file-sharing", "threat/content name": "HTTP OPTIONS Method", "id": -1},
 {"risk": "5", "application": "ftp", "category": "general-internet", "subcategory": "file-sharing", "threat/content name": "FTP Login Failed", "id": -1},
 {"risk": "4", "application": "sip", "category": "collaboration", "subcategory": "voip-video", "threat/content name": "SIP Register Request Attempt", "id": -1},
 {"risk": "4", "application": "sip", "category": "collaboration", "subcategory": "voip-video", "threat/content name": "SIP Register Message Brute-force Attack", "id": -1},
 {"risk": "4", "application": "ssh", "category": "networking", "subcategory": "encrypted-tunnel", "threat/content name": "SSH2 Login Attempt", "id": -1},
 {"risk": "4", "application": "ssl", "category": "networking", "subcategory": "encrypted-tunnel", "threat/content name": "SSL Renegotiation Denial of Service Vulnerability", "id": -1},
 {"risk": "4", "application": "web-browsing", "category": "general-internet", "subcategory": "internet-utility", "threat/content name": "HTTP Unauthorized Error", "id": -1},
 {"risk": "4", "application": "facebook-base", "category": "collaboration", "subcategory": "social-networking", "threat/content name": "SSL Renegotiation Denial of Service Vulnerability", "id": -1},
 {"risk": "4", "application": "web-browsing", "category": "general-internet", "subcategory": "internet-utility", "threat/content name": "HTTP WWW-Authentication Failed", "id": -1},
 {"risk": "4", "application": "web-browsing", "category": "general-internet", "subcategory": "internet-utility", "threat/content name": "Generic GET Method Buffer Overflow Vulnerability", "id": -1},
 {"risk": "4", "application": "web-browsing", "category": "general-internet", "subcategory": "internet-utility", "threat/content name": "HTTP OPTIONS Method", "id": -1},
 {"risk": "4", "application": "sip", "category": "collaboration", "subcategory": "voip-video", "threat/content name": "Microsoft Communicator INVITE Flood Denial of Service Vulnerability", "id": -1},
 {"risk": "4", "application": "dns", "category": "networking", "subcategory": "infrastructure", "threat/content name": "Suspicious DNS Query (generic:api.greygray.biz)", "id": -1},
 {"risk": "4", "application": "dns", "category": "networking", "subcategory": "infrastructure", "threat/content name": "Suspicious DNS Query (PWS.fapk:advombat.ru)", "id": -1},
 {"risk": "4", "application": "dns", "category": "networking", "subcategory": "infrastructure", "threat/content name": "Suspicious DNS Query (generic:ibnlive.in.com)", "id": -1},
 {"risk": "4", "application": "sip", "category": "collaboration", "subcategory": "voip-video", "threat/content name": "SIP Bye Request Attempt", "id": -1},
 {"risk": "4", "application": "web-browsing", "category": "general-internet", "subcategory": "internet-utility", "threat/content name": "HTTP GET Requests Long URI Anomaly", "id": -1},
 {"risk": "4", "application": "web-browsing", "category": "general-internet", "subcategory": "internet-utility", "threat/content name": "JavaScript Obfuscation Detected", "id": -1},
 {"risk": "4", "application": "dns", "category": "networking", "subcategory": "infrastructure", "threat/content name": "Suspicious DNS Query (generic:api.megabrowse.biz)", "id": -1},
 {"risk": "4", "application": "dns", "category": "networking", "subcategory": "infrastructure", "threat/content name": "Suspicious DNS Query (Trojan-Dropper.sysn:ak.imgfarm.com)", "id": -1},
 {"risk": "4", "application": "ssh", "category": "networking", "subcategory": "encrypted-tunnel", "threat/content name": "SSH User Authentication Brute-force Attempt", "id": -1},
 {"risk": "4", "application": "dns", "category": "networking", "subcategory": "infrastructure", "threat/content name": "DNS ANY Request", "id": -1},
 {"risk": "4", "application": "web-browsing", "category": "general-internet", "subcategory": "internet-utility", "threat/content name": "Microsoft ASP.NET Remote Unauthenticated Denial of Service Vulnerability", "id": -1},
 {"risk": "4", "application": "web-browsing", "category": "general-internet", "subcategory": "internet-utility", "threat/content name": "Adobe PDF File With Embedded Javascript", "id": -1},
 {"risk": "4", "application": "dns", "category": "networking", "subcategory": "infrastructure", "threat/content name": "Suspicious DNS Query (generic:tracker.ccc.se)", "id": -1},
 {"risk": "4", "application": "gmail-base", "category": "collaboration", "subcategory": "email", "threat/content name": "SSL Renegotiation Denial of Service Vulnerability", "id": -1},
 {"risk": "4", "application": "dns", "category": "networking", "subcategory": "infrastructure", "threat/content name": "Suspicious DNS Query (generic:cdn.ministerial5.com)", "id": -1},
 {"risk": "4", "application": "web-browsing", "category": "general-internet", "subcategory": "internet-utility", "threat/content name": "Microsoft ASP.Net Information Leak Vulnerability", "id": -1},
 {"risk": "4", "application": "sip", "category": "collaboration", "subcategory": "voip-video", "threat/content name": "Sipvicious.Gen User-Agent Traffic", "id": -1},
 {"risk": "4", "application": "dns", "category": "networking", "subcategory": "infrastructure", "threat/content name": "Suspicious DNS Query (generic:s.m2pub.com)", "id": -1},
 {"risk": "4", "application": "yahoo-voice", "category": "collaboration", "subcategory": "voip-video", "threat/content name": "SIP Register Request Attempt", "id": -1},
 {"risk": "-1", "threat/content name": "Suspicious TLS Evasion Found", "id": 14978, "application": "", "category": "", "subcategory": ""},
 {"risk": "-1", "threat/content name": "Windows SMB Login Attempt", "id": 31696, "application": "", "category": "", "subcategory": ""},
 {"risk": "-1", "threat/content name": "POODLE Bites Vulnerability", "id": 37144, "application": "", "category": "", "subcategory": ""},
 {"risk": "-1", "threat/content name": "Microsoft Windows user enumeration", "id": 30842, "application": "", "category": "", "subcategory": ""},
 {"risk": "-1", "threat/content name": "Microsoft Windows SMB Negotiate Request", "id": 35364, "application": "", "category": "", "subcategory": ""},
 {"risk": "-1", "threat/content name": "NetBIOS null session", "id": 31710, "application": "", "category": "", "subcategory": ""},
 {"risk": "-1", "threat/content name": "Suspicious HTTP Evasion Found", "id": 14984, "application": "", "category": "", "subcategory": ""},
 {"risk": "-1", "threat/content name": "DER Encoded X509 Certificate", "id": 52209, "application": "", "category": "", "subcategory": ""},
 {"risk": "-1", "threat/content name": "SSH2 Login Attempt", "id": 31914, "application": "", "category": "", "subcategory": ""},
 {"risk": "-1", "threat/content name": "NetBIOS nbtstat query", "id": 31707, "application": "", "category": "", "subcategory": ""},
 {"risk": "-1", "threat/content name": "Non-RFC Compliant TELNET Traffic on Port 23", "id": 56484, "application": "", "category": "", "subcategory": ""},
 {"risk": "-1", "threat/content name": "HTTP Unauthorized Error", "id": 34556, "application": "", "category": "", "subcategory": ""},
 {"risk": "-1", "threat/content name": "HTTP WWW-Authentication Failed", "id": 31708, "application": "", "category": "", "subcategory": ""},
 {"risk": "-1", "threat/content name": "HTTP Non-RFC Compliant Request", "id": 39143, "application": "", "category": "", "subcategory": ""},
 {"risk": "-1", "threat/content name": "SMB: User Password Brute Force Attempt", "id": 40004, "application": "", "category": "", "subcategory": ""},
 {"risk": "-1", "threat/content name": "Email Link", "id": 52143, "application": "", "category": "", "subcategory": ""},
 {"risk": "-1", "threat/content name": "HTTP OPTIONS Method", "id": 30520, "application": "", "category": "", "subcategory": ""},
 {"risk": "-1", "threat/content name": "Use of insecure SSLv3.0 Found in Server Response", "id": 36815, "application": "", "category": "", "subcategory": ""},
 {"risk": "-1", "threat/content name": "Non-RFC Compliant SMTP Traffic on Port 25", "id": 56953, "application": "", "category": "", "subcategory": ""},
 {"risk": "-1", "threat/content name": "SIP Register Request Attempt", "id": 33592, "application": "", "category": "", "subcategory": ""},
 {"risk": "-1", "threat/content name": "IMP4 Detected", "id": 52104, "application": "", "category": "", "subcategory": ""},
 {"risk": "-1", "threat/content name": "Abnormal SSL traffic on port 443", "id": 54699, "application": "", "category": "", "subcategory": ""},
 {"risk": "-1", "threat/content name": "SSH2 Failed Login Attempt", "id": 55873, "application": "", "category": "", "subcategory": ""},
 {"risk": "-1", "threat/content name": "JavaScript Obfuscation Detected", "id": 54261, "application": "", "category": "", "subcategory": ""},
 {"risk": "-1", "threat/content name": "Windows Local Security Architect LsarQuerylnformationPolicy", "id": 30858, "application": "", "category": "", "subcategory": ""},
 {"risk": "-1", "threat/content name": "Service Enum Through SMB ServiceEnum2", "id": 30867, "application": "", "category": "", "subcategory": ""},
 {"risk": "-1", "threat/content name": "Microsoft MSOFFICE", "id": 52033, "application": "", "category": "", "subcategory": ""},
 {"risk": "-1", "threat/content name": "Microsoft Windows Registry Read Attempt", "id": 34940, "application": "", "category": "", "subcategory": ""},
 {"risk": "-1", "threat/content name": "Non-RFC Compliant TELNET Traffic on Port 23", "id": 56551, "application": "", "category": "", "subcategory": ""},
 {"risk": "-1", "threat/content name": "Failed Authentication Through Mail Protocol", "id": 31709, "application": "", "category": "", "subcategory": ""},
 {"risk": "-1", "threat/content name": "Microsoft Windows Registry Enumeration", "id": 30840, "application": "", "category": "", "subcategory": ""},
 {"risk": "-1", "threat/content name": "Microsoft Windows SMB Remote Code Execution Vulnerability", "id": 32422, "application": "", "category": "", "subcategory": ""},
 {"risk": "-1", "threat/content name": "Windows Local Security Architect Isardelete access", "id": 30857, "application": "", "category": "", "subcategory": ""},
 {"risk": "-1", "threat/content name": "LDAP Authentication Via BIND Request Failed", "id": 31706, "application": "", "category": "", "subcategory": ""}]
