#!/usr/bin/env python3
import sys
import os
import re
import pprint
import time
import datetime
from scapy.all import wrpcap
from scapy.utils import PcapWriter
import pyami

from pcraft.Application import *


loop_tracker = {} # We track our loops by name
is_in_loop = None

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Syntax: %s script.ami output.pcap" % sys.argv[0])
        sys.exit(1)

    print("Opening Script File %s" % sys.argv[1])
    
    app = Application(scenariofile=sys.argv[1], pcap_out=sys.argv[2])

    app.finalize()
    
